-- ============================================================
-- kabSUBO Advanced SQL Features
-- Trigger, Stored Procedure, View, Transaction
-- ADBMS class requirements
-- ============================================================

USE kabsubo;

-- ============================================================
-- 1. TRIGGER: Auto-generate slug from place name
-- Fires BEFORE INSERT on places table
-- Converts "Main Gate Grill" → "main-gate-grill"
-- ============================================================
DELIMITER //

CREATE OR REPLACE TRIGGER before_insert_places
BEFORE INSERT ON places
FOR EACH ROW
BEGIN
    SET NEW.slug = LOWER(
        REGEXP_REPLACE(
            REGEXP_REPLACE(NEW.name, '[^a-zA-Z0-9\\s-]', ''),
            '\\s+', '-'
        )
    );

    IF NEW.slug = '' THEN
        SET NEW.slug = LOWER(UUID());
    END IF;
END//

DELIMITER ;

-- ============================================================
-- 2. STORED PROCEDURE + TRANSACTION
-- submit_place_with_audit:
--   Inserts a new place AND creates an audit log entry
--   inside a single transaction (COMMIT / ROLLBACK)
--
-- Parameters:
--   p_name        VARCHAR(255)  — place name
--   p_type        VARCHAR(20)   — place type ENUM value
--   p_lat         DECIMAL(9,6)  — latitude
--   p_lng         DECIMAL(9,6)  — longitude
--   p_submitted_by CHAR(36)     — UUID of the submitting user
-- ============================================================
DELIMITER //

CREATE OR REPLACE PROCEDURE submit_place_with_audit(
    IN p_place_id     CHAR(36),
    IN p_audit_id     CHAR(36),
    IN p_name         VARCHAR(255),
    IN p_type         VARCHAR(50),
    IN p_lat          DECIMAL(9,6),
    IN p_lng          DECIMAL(9,6),
    IN p_address      VARCHAR(500),
    IN p_submitted_by CHAR(36),
    IN p_description  TEXT,
    IN p_hours_json   JSON,
    IN p_price_range  VARCHAR(50),
    IN p_photo_urls   JSON,
    IN p_contact      VARCHAR(100)
)
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        ROLLBACK;
        RESIGNAL;
    END;

    START TRANSACTION;

    -- Insert the place with explicit UUID (slug is auto-generated by trigger)
    INSERT INTO places (id, name, type, lat, lng, address, submitted_by, status, description, hours_json, price_range, photo_urls, contact)
    VALUES (p_place_id, p_name, p_type, p_lat, p_lng, p_address, p_submitted_by, 'pending', p_description, p_hours_json, p_price_range, p_photo_urls, p_contact);

    -- Log the submission in the audit table
    INSERT INTO submissions_audit (id, place_id, actor_id, action, notes)
    VALUES (p_audit_id, p_place_id, p_submitted_by, 'pending', 'Submitted via stored procedure.');

    COMMIT;
END//

DELIMITER ;

-- ============================================================
-- 3. VIEW: Place Summary
-- Shows each place with its average rating, menu item count,
-- and the most recent audit action.
-- ============================================================
CREATE OR REPLACE VIEW place_summary_view AS
SELECT
    p.id,
    p.name,
    p.slug,
    p.type,
    p.status,
    p.lat,
    p.lng,
    p.address,
    p.price_range,
    p.contact,
    p.created_at,
    COALESCE(rev.avg_rating, 0)          AS avg_rating,
    COALESCE(rev.review_count, 0)        AS review_count,
    COALESCE(menu.menu_item_count, 0)    AS menu_item_count,
    sa.latest_action,
    sa.latest_action_at
FROM places p
LEFT JOIN (
    SELECT
        place_id,
        AVG(rating) AS avg_rating,
        COUNT(id) AS review_count
    FROM reviews
    GROUP BY place_id
) rev ON rev.place_id = p.id
LEFT JOIN (
    SELECT
        place_id,
        COUNT(id) AS menu_item_count
    FROM menu_items
    GROUP BY place_id
) menu ON menu.place_id = p.id
LEFT JOIN (
    SELECT
        place_id,
        action   AS latest_action,
        created_at AS latest_action_at,
        ROW_NUMBER() OVER (
            PARTITION BY place_id
            ORDER BY created_at DESC, id DESC
        ) AS rn
    FROM submissions_audit
) sa ON sa.place_id = p.id AND sa.rn = 1;

-- ============================================================
-- 4. Usage Example: Calling the stored procedure
-- ============================================================
-- CALL submit_place_with_audit(
--     'New Food Spot',
--     'stall',
--     14.1950,
--     120.8810,
--     'Example address, Indang',
--     'user-bongalos'
-- );
--
-- SELECT * FROM place_summary_view WHERE status = 'approved';
